language: ruby
rvm:
  - 2.1.4

env:
  CODECLIMATE_REPO_TOKEN=80a6c1890ff5b568fa7f62fea8c9b388cfef4d819f70411b615db61bc6a365ad

bundler_args: --path=vendor/bundle --without production

before_script:
  - sh -c "RAILS_ENV=test bundle exec rake db:create"

notifications:
  flowdock: 7810528ead9733543fd77e874400b1c1
