NEXT_AVAILABLE_DAYS_COUNT = 10
START_DAYS_COUNT = 1
CROSSROADS_TRUCK_COST = 600
DONOR_APP = "app.goodcity"
ADMIN_APP = "admin.goodcity"
GGV_POLL_JOB_WAIT_TIME = 1.minute # 5.seconds
SYSTEM_USER_MOBILE = "+85264522773"
