NEXT_AVAILABLE_DAYS_COUNT = 40
START_DAYS_COUNT = 0
CROSSROADS_TRUCK_COST = 600
DONOR_APP = "app.goodcity"
ADMIN_APP = "admin.goodcity"
STOCK_APP = "stock.goodcity"
BROWSE_APP = "browse.goodcity"
STOCKIT_APP = "stockit"
STAFF_APPS = [ADMIN_APP, STOCK_APP, STOCKIT_APP]
GGV_POLL_JOB_WAIT_TIME = 60.seconds
GGV_POLL_JOB_WAIT_TIME_FOR_ONLINE_DONOR = 30.seconds
SYSTEM_USER_MOBILE = "+85264522773"
GOODCITY_NUMBER = "+85222729345"
TWILIO_QUEUE_WAIT_TIME = 30
STOCKIT_PREFIX = "X"

