base: &BASE
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio:
    account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
    phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>
    workflow_sid: <%= ENV['TWILIO_WORKFLOW_SID'] %>
    workspace_sid: <%= ENV['TWILIO_WORKSPACE_SID'] %>
    call_app_sid: <%= ENV['TWILIO_CALL_APP_SID'] %>
    voice_number: <%= ENV['TWILIO_VOICE_NUMBER'] %>
    api_key: <%= ENV['TWILIO_API_KEY'] %>
    twilio_secret: <%= ENV['TWILIO_SECRET'] %>
  jwt:
    secret_key: <%= ENV['JWT_SECRET_KEY'] %>
    hmac_sha_algo: <%= ENV['JWT_HMAC_SHA_ALGO'] %>
    issuer: <%= ENV['JWT_ISSUER'] %>
    validity: <%= ENV['JWT_VALIDITY'] %>
    validity_for_api: <%= ENV['JWT_VALIDITY_FOR_API']%>
    validity_for_otp: <%= ENV['OTP_CODE_VALIDITY'] %>
  hasura:
    secret_key: <%= ENV['HASURA_JWT_SECRET_KEY'] %>
    hmac_sha_algo: <%= ENV['HASURA_JWT_HMAC_SHA_ALGO'] %>
    issuer: <%= ENV['HASURA_JWT_ISSUER'] %>
    audience: <%= ENV['HASURA_JWT_AUDIENCE'] %>
    validity: <%= ENV['HASURA_JWT_VALIDITY'] %>
  token:
    otp_code_validity: <%= ENV['OTP_CODE_VALIDITY'] %>
  cloudinary:
    cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
    api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
    api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
    enhance_image_tag: true
    static_image_support: <%= Rails.env.production? %>
  azure_notifications:
    admin:
      endpoint: <%= ENV['AZURE_NOTIFICATION_ADMINHUB_ENDPOINT'] %>
      key_name: <%= ENV['AZURE_NOTIFICATION_ADMINHUB_KEY_NAME'] %>
      key: <%= ENV['AZURE_NOTIFICATION_ADMINHUB_KEY'] %>
    app:
      endpoint: <%= ENV['AZURE_NOTIFICATION_HUB_ENDPOINT'] %>
      key_name: <%= ENV['AZURE_NOTIFICATION_HUB_KEY_NAME'] %>
      key: <%= ENV['AZURE_NOTIFICATION_HUB_KEY'] %>
    stock:
      endpoint: <%= ENV['AZURE_NOTIFICATION_STOCKHUB_ENDPOINT'] %>
      key_name: <%= ENV['AZURE_NOTIFICATION_STOCKHUB_KEY_NAME'] %>
      key: <%= ENV['AZURE_NOTIFICATION_STOCKHUB_KEY'] %>
    browse:
      endpoint: <%= ENV['AZURE_NOTIFICATION_BROWSEHUB_ENDPOINT'] %>
      key_name: <%= ENV['AZURE_NOTIFICATION_BROWSEHUB_KEY_NAME'] %>
      key: <%= ENV['AZURE_NOTIFICATION_BROWSEHUB_KEY'] %>
  socketio_service:
    url: <%= ENV['SOCKETIO_SERVICE_URL'] %>
  barcode:
    printer_name: <%=ENV['BARCODE_PRINTER_NAME']%>
    printer_host: <%=ENV['BARCODE_PRINTER_HOST']%>
    printer_user: <%=ENV['BARCODE_PRINTER_USER']%>
    printer_pwd: <%=ENV['BARCODE_PRINTER_PWD']%>
  appstore_reviewer_login:
    number: '<%= ENV['APPSTORE_REVIEWER_LOGIN_NUMBER'] %>'
    pin: '<%= ENV['APPSTORE_REVIEWER_LOGIN_PIN'] %>'

development:
  <<: *BASE
  base_urls:
    app: http://localhost:4200
    admin: http://localhost:4201

test:
  <<: *BASE
  secret_key_base: 5b405f98de7d
  jwt:
    secret_key: 2332dasdc
    hmac_sha_algo: HS256
    issuer: GoodCityHK
    validity: 12000
    validity_for_api: 31536000
    validity_for_otp: 1800
  token:
    otp_code_validity: 30
  base_urls:
    app: http://localhost:4200
    admin: http://localhost:4201

staging:
  <<: *BASE
  base_urls:
    app: https://app-staging.goodcity.hk
    admin: https://admin-staging.goodcity.hk

preview:
  <<: *BASE
  base_urls:
    app: https://app-preview.goodcity.hk
    admin: https://admin-preview.goodcity.hk

production:
  <<: *BASE
  base_urls:
    app: https://app.goodcity.hk
    admin: https://admin.goodcity.hk
