# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

base: &BASE
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  twilio:
    account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
    phone_number: <%= ENV['TWILIO_PHONE_NUMBER'] %>
    workflow_sid: <%= ENV['TWILIO_WORKFLOW_SID'] %>
    workspace_sid: <%= ENV['TWILIO_WORKSPACE_SID'] %>
    call_app_sid: <%= ENV['TWILIO_CALL_APP_SID'] %>
    voice_number: <%= ENV['TWILIO_VOICE_NUMBER'] %>
  jwt:
    secret_key: <%= ENV['JWT_SECRET_KEY'] %>
    hmac_sha_algo: <%= ENV['JWT_HMAC_SHA_ALGO'] %>
    issuer: <%= ENV['JWT_ISSUER'] %>
    validity: <%= ENV['JWT_VALIDITY'] %>
  token:
    otp_code_validity: <%= ENV['OTP_CODE_VALIDITY'] %>
  cloudinary:
    cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
    api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
    api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
    enhance_image_tag: true
    static_image_support: <%= Rails.env.production? %>
  azure_notifications:
    admin:
      endpoint: <%= ENV['AZURE_NOTIFICATION_ADMINHUB_ENDPOINT'] %>
      key_name: <%= ENV['AZURE_NOTIFICATION_ADMINHUB_KEY_NAME'] %>
      key: <%= ENV['AZURE_NOTIFICATION_ADMINHUB_KEY'] %>
    donor:
      endpoint: <%= ENV['AZURE_NOTIFICATION_HUB_ENDPOINT'] %>
      key_name: <%= ENV['AZURE_NOTIFICATION_HUB_KEY_NAME'] %>
      key: <%= ENV['AZURE_NOTIFICATION_HUB_KEY'] %>
  socketio_service:
    url: <%= ENV['SOCKETIO_SERVICE_URL'] %>

development:
  <<: *BASE
  base_urls:
    app: http://localhost:4200
    admin: http://localhost:4201

test:
  <<: *BASE
  base_urls:
    app: http://localhost:4200
    admin: http://localhost:4201

staging:
  <<: *BASE
  base_urls:
    app: https://app-staging.goodcity.hk
    admin: https://admin-staging.goodcity.hk

production:
  <<: *BASE
  base_urls:
    app: https://app.goodcity.hk
    admin: https://admin.goodcity.hk
  appstore_reviewer_login:
    number: '<%= ENV['APPSTORE_REVIEWER_LOGIN_NUMBER'] %>'
    pin: '<%= ENV['APPSTORE_REVIEWER_LOGIN_PIN'] %>'
