class AddMissingForeignKeys < ActiveRecord::Migration
  def change
    add_foreign_key "addresses", "districts", name: "addresses_district_id_fk"
    add_foreign_key "auth_tokens", "users", name: "auth_tokens_user_id_fk"
    add_foreign_key "beneficiaries", "users", column: "created_by_id", name: "beneficiaries_created_by_id_fk"
    add_foreign_key "boxes", "pallets", name: "boxes_pallet_id_fk"
    add_foreign_key "computer_accessories", "lookups", column: "comp_test_status_id", name: "computer_accessories_comp_test_status_id_fk"
    add_foreign_key "computer_accessories", "countries", name: "computer_accessories_country_id_fk"
    add_foreign_key "computers", "lookups", column: "comp_test_status_id", name: "computers_comp_test_status_id_fk"
    add_foreign_key "computers", "countries", name: "computers_country_id_fk"
    add_foreign_key "deliveries", "contacts", name: "deliveries_contact_id_fk"
    add_foreign_key "deliveries", "gogovan_orders", name: "deliveries_gogovan_order_id_fk"
    add_foreign_key "deliveries", "offers", name: "deliveries_offer_id_fk"
    add_foreign_key "deliveries", "schedules", name: "deliveries_schedule_id_fk"
    add_foreign_key "districts", "territories", name: "districts_territory_id_fk"
    add_foreign_key "electricals", "countries", name: "electricals_country_id_fk"
    add_foreign_key "electricals", "lookups", column: "frequency_id", name: "electricals_frequency_id_fk"
    add_foreign_key "electricals", "lookups", column: "test_status_id", name: "electricals_test_status_id_fk"
    add_foreign_key "electricals", "lookups", column: "voltage_id", name: "electricals_voltage_id_fk"
    add_foreign_key "goodcity_requests", "users", column: "created_by_id", name: "goodcity_requests_created_by_id_fk"
    add_foreign_key "items", "donor_conditions", name: "items_donor_condition_id_fk"
    add_foreign_key "items", "offers", name: "items_offer_id_fk"
    add_foreign_key "items", "package_types", name: "items_package_type_id_fk"
    add_foreign_key "items", "rejection_reasons", name: "items_rejection_reason_id_fk"
    add_foreign_key "medicals", "countries", name: "medicals_country_id_fk"
    add_foreign_key "messages", "users", column: "sender_id", name: "messages_sender_id_fk"
    add_foreign_key "offers", "cancellation_reasons", name: "offers_cancellation_reason_id_fk"
    add_foreign_key "offers", "users", column: "closed_by_id", name: "offers_closed_by_id_fk"
    add_foreign_key "offers", "companies", name: "offers_company_id_fk"
    add_foreign_key "offers", "users", column: "created_by_id", name: "offers_created_by_id_fk"
    add_foreign_key "offers", "crossroads_transports", name: "offers_crossroads_transport_id_fk"
    add_foreign_key "offers", "gogovan_transports", name: "offers_gogovan_transport_id_fk"
    add_foreign_key "offers", "users", column: "received_by_id", name: "offers_received_by_id_fk"
    add_foreign_key "offers", "users", column: "reviewed_by_id", name: "offers_reviewed_by_id_fk"
    add_foreign_key "order_transports", "contacts", name: "order_transports_contact_id_fk"
    add_foreign_key "order_transports", "gogovan_orders", name: "order_transports_gogovan_order_id_fk"
    add_foreign_key "order_transports", "gogovan_transports", name: "order_transports_gogovan_transport_id_fk"
    add_foreign_key "order_transports", "orders", name: "order_transports_order_id_fk"
    add_foreign_key "orders", "addresses", name: "orders_address_id_fk"
    add_foreign_key "orders", "beneficiaries", name: "orders_beneficiary_id_fk"
    add_foreign_key "orders", "booking_types", name: "orders_booking_type_id_fk"
    add_foreign_key "orders", "cancellation_reasons", name: "orders_cancellation_reason_id_fk"
    add_foreign_key "orders", "users", column: "cancelled_by_id", name: "orders_cancelled_by_id_fk"
    add_foreign_key "orders", "users", column: "closed_by_id", name: "orders_closed_by_id_fk"
    add_foreign_key "orders", "countries", name: "orders_country_id_fk"
    add_foreign_key "orders", "users", column: "created_by_id", name: "orders_created_by_id_fk"
    add_foreign_key "orders", "stockit_local_orders", column: "detail_id", name: "orders_detail_id_fk"
    add_foreign_key "orders", "users", column: "dispatch_started_by_id", name: "orders_dispatch_started_by_id_fk"
    add_foreign_key "orders", "districts", name: "orders_district_id_fk"
    add_foreign_key "orders", "organisations", name: "orders_organisation_id_fk"
    add_foreign_key "orders_packages", "orders", name: "orders_packages_order_id_fk"
    add_foreign_key "orders_packages", "packages", name: "orders_packages_package_id_fk"
    add_foreign_key "orders_packages", "users", column: "updated_by_id", name: "orders_packages_updated_by_id_fk"
    add_foreign_key "orders", "users", column: "process_completed_by_id", name: "orders_process_completed_by_id_fk"
    add_foreign_key "orders", "users", column: "processed_by_id", name: "orders_processed_by_id_fk"
    add_foreign_key "orders_purposes", "orders", name: "orders_purposes_order_id_fk"
    add_foreign_key "orders_purposes", "purposes", name: "orders_purposes_purpose_id_fk"
    add_foreign_key "orders", "stockit_activities", name: "orders_stockit_activity_id_fk"
    add_foreign_key "orders", "stockit_contacts", name: "orders_stockit_contact_id_fk"
    add_foreign_key "orders", "stockit_organisations", name: "orders_stockit_organisation_id_fk"
    add_foreign_key "orders", "users", column: "submitted_by_id", name: "orders_submitted_by_id_fk"
    add_foreign_key "package_categories_package_types", "package_categories", name: "package_categories_package_types_package_category_id_fk"
    add_foreign_key "package_categories_package_types", "package_types", name: "package_categories_package_types_package_type_id_fk"
    add_foreign_key "package_categories", "package_categories", column: "parent_id", name: "package_categories_parent_id_fk"
    add_foreign_key "package_sets", "package_types", name: "package_sets_package_type_id_fk"
    add_foreign_key "package_types", "locations", name: "package_types_location_id_fk"
    add_foreign_key "packages", "boxes", name: "packages_box_id_fk"
    add_foreign_key "packages", "donor_conditions", name: "packages_donor_condition_id_fk"
    add_foreign_key "packages", "items", name: "packages_item_id_fk"
    add_foreign_key "packages_locations", "locations", name: "packages_locations_location_id_fk"
    add_foreign_key "packages_locations", "packages", name: "packages_locations_package_id_fk"
    add_foreign_key "packages", "orders", name: "packages_order_id_fk"
    add_foreign_key "packages", "package_sets", name: "packages_package_set_id_fk"
    add_foreign_key "packages", "package_types", name: "packages_package_type_id_fk"
    add_foreign_key "packages", "pallets", name: "packages_pallet_id_fk"
    add_foreign_key "packages", "restrictions", name: "packages_restriction_id_fk"
    add_foreign_key "packages", "users", column: "stockit_designated_by_id", name: "packages_stockit_designated_by_id_fk"
    add_foreign_key "packages", "users", column: "stockit_moved_by_id", name: "packages_stockit_moved_by_id_fk"
    add_foreign_key "packages", "users", column: "stockit_sent_by_id", name: "packages_stockit_sent_by_id_fk"
    add_foreign_key "packages", "storage_types", name: "packages_storage_type_id_fk"
    add_foreign_key "printers", "locations", name: "printers_location_id_fk"
    add_foreign_key "requested_packages", "packages", name: "requested_packages_package_id_fk"
    add_foreign_key "requested_packages", "users", name: "requested_packages_user_id_fk"
    add_foreign_key "role_permissions", "permissions", name: "role_permissions_permission_id_fk"
    add_foreign_key "role_permissions", "roles", name: "role_permissions_role_id_fk"
    add_foreign_key "stocktake_revisions", "users", column: "created_by_id", name: "stocktake_revisions_created_by_id_fk"
    add_foreign_key "stocktakes", "users", column: "created_by_id", name: "stocktakes_created_by_id_fk"
    add_foreign_key "subpackage_types", "package_types", name: "subpackage_types_package_type_id_fk"
    add_foreign_key "subpackage_types", "package_types", column: "subpackage_type_id", name: "subpackage_types_subpackage_type_id_fk"
    add_foreign_key "subscriptions", "messages", name: "subscriptions_message_id_fk"
    add_foreign_key "subscriptions", "users", name: "subscriptions_user_id_fk"
    add_foreign_key "user_roles", "roles", name: "user_roles_role_id_fk"
    add_foreign_key "user_roles", "users", name: "user_roles_user_id_fk"
    add_foreign_key "users", "images", name: "users_image_id_fk"
  end
end
